import { Inter } from "next/font/google";
import "@/app/styles/_destyle.scss";
import "@/app/styles/_global.scss";
import "@/app/styles/_utility.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="ja">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
